# Generated by Django 4.2.11 on 2025-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id_aplicacion",
                    models.IntegerField(
                        db_column="id_aplicacion", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="descripcion", max_length=200, null=True
                    ),
                ),
                ("start_date", models.DateField(db_column="fecha_ini")),
                (
                    "end_date",
                    models.DateField(blank=True, db_column="fecha_fin", null=True),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "aplicacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationUser",
            fields=[
                (
                    "id_aplicacion_usuario",
                    models.BigAutoField(
                        db_column="id_aplicacion_usuario",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_column="username", max_length=50)),
                ("fecha_ini", models.DateField(db_column="fecha_ini")),
                (
                    "fecha_fin",
                    models.DateField(blank=True, db_column="fecha_fin", null=True),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "provider",
                    models.CharField(
                        blank=True, db_column="provider", max_length=255, null=True
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, db_column="provider_id", max_length=255, null=True
                    ),
                ),
                (
                    "remember_token",
                    models.CharField(
                        blank=True,
                        db_column="remember_token",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("estado_sesion", models.IntegerField(db_column="estado_sesion")),
                (
                    "fecha_validacion",
                    models.DateField(
                        blank=True, db_column="fecha_validacion", null=True
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True, db_column="dni", max_length=50, null=True
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, db_column="nombres", max_length=255, null=True
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, db_column="apellidos", max_length=255, null=True
                    ),
                ),
                (
                    "estado_validacion",
                    models.IntegerField(db_column="estado_validacion"),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, db_column="pais", max_length=100, null=True
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, db_column="refresh_token", max_length=255, null=True
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, db_column="avatar", max_length=255, null=True
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, db_column="password", max_length=1024, null=True
                    ),
                ),
                (
                    "old_id",
                    models.IntegerField(blank=True, db_column="old_id", null=True),
                ),
                (
                    "fecha_purga",
                    models.DateField(blank=True, db_column="fecha_purga", null=True),
                ),
            ],
            options={
                "verbose_name": "Application User",
                "verbose_name_plural": "Application Users",
                "db_table": "aplicacion_usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("attribute_list", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "rol_aplicacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("permitted_object", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("business_unit_id", models.CharField(max_length=10)),
                ("user_id", models.IntegerField()),
                ("country", models.CharField(max_length=10)),
                ("status", models.IntegerField()),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "usuario_rol",
                "managed": False,
            },
        ),
    ]
